---
date: "2016-05-05T21:48:51-07:00"
title: Acerca de
---

```{=html}
<style>
#TOC {

  color: #99A7DE;
  background-color: #F5F5F5;

}
#header {
  
  text-align: center;
  color: #A36DD0;
  background-color: #F5F5F5;
  opacity: 0.8;
  font-family: serif;
  
}
h1, h2, h3, h4 {
  
  color: #99A7DE;
  opacity: 0.8;

}
body {

    font-family: cambria;
    text-align:justify;
    background-color: #F5F5F5;
    
}
pre {

    font-family: Serif;
    
}
</style>

```

**Phylo Galaxy** es un espacio de recursos académicos y profesionales dedicado a la exploración de la metagenómica, con un enfoque particular en la herramienta **phyloseq**.

La metagenómica, que implica el análisis del ADN de comunidades microbianas, ha permitido a los científicos catalogar y comprender la diversidad de vida microbiana presente en una variedad de ambientes. La recolección y análisis de estos datos, sin embargo, presenta desafíos significativos debido a su volumen y complejidad. Phyloseq, un paquete de R, ofrece una solución a este desafío, proporcionando una variedad de funcionalidades para el análisis y la visualización de datos metagenómicos de alto rendimiento.

En Phylo Galaxy, se presentará la metagenómica y sus herramientas asociadas de una manera accesible y detallada. Nuestro objetivo es proporcionar una guía clara y precisa para aquellos que buscan comprender y aplicar las técnicas de metagenómica en su trabajo de investigación. Se explicará así cómo usar phyloseq y otras herramientas, se presentarán los avances más recientes en el campo de la metagenómica, y se proporcionará una orientación sobre la interpretación de los resultados del análisis metagenómico.

Phylo Galaxy está diseñado para servir tanto a los profesionales de la ciencia que buscan expandir su conjunto de herramientas, como a los estudiantes en el campo de la genómica y a cualquier aficionado interesado en el análisis metagenómico.

Bienvenido a Phylo Galaxy. ¡Esperamos que este recurso le sea útil en su exploración de la metagenómica!


Este blog ha sido desarrollado con [**blogdown**](https://github.com/rstudio/blogdown). 
